#+TITLE: Exam R II
#+OPTIONS: toc:nil num:nil
#+PROPERTY: header-args  :session :exports both
* Description
The exam will take the form of MCQs. There will be 3 types of questions.
•questions about R and programming (5p)
•questions about understanding of R scripts (10p)
•questions asking you to use R in order to make calculations (5p)

<TBD>
... In addition, there will be a bonus of 1 or 2 points for the prediction.
Solutions with a predictionR2between 0.7 and 0.85 will get one additional
point. Solutions with a prediction R2 larger than 0.85 will get two additional
points.
<TBD>

* Questions about R
** Question 1
What does the function x[-(1:n)] returns:
- elements of x from n to the beginning
- elements of x from n+1 to the end
- elements of x from n to the end
- elements of x from n+1 to the beginning
** Question 2
The function subset() admits 3 arguments. The third argument represents:
- the observations to select
- the data frame names
- the variables to select
- a condition
* Questions about interpretations of R code  
** Question 3
We wish to estimate mean price of red cars. Which command can we use ?
- mean(cars$price[color == "red"])
- mean(cars$price[cars$color == "red"])
- mean(cars[cars$color == "red", "price"], na.rm=TRUE)
- mean(cars[cars$mileage = "red", "price"], na.rm=TRUE)
** Question 4
Which command would return the same value as the following chunk:
#+begin_src r 
round(prop.table(table(cars$brand)),2)
#+end_src
-
-
-
- round(table(cars$brand, useNA ="no")/nrow(cars),2) 
* Questions about production of R code
We use a data set containing mental health in jail data. every observation
corresponds to an interview conducted with an inmate. The data set is available
in the file : "smp2.csv"
** Question 5
How many inmates are employees ?
- 31
- 58
- 90
- 222
** Question 6
Run an OLS regressions to estimate the model log(dur.interv)= a + b*log(age) + bruit. What is the estimated
value of the coeﬃcient b ? (dur.interv represents the interview duration)
- -1.712
- 0.02
- 0.13
- 2.35


